"""Market route - product recommendations based on disease/crop"""
from flask import Blueprint, request, jsonify

market_bp = Blueprint("market", __name__)

PRODUCTS = [
    # ── Fungicides ──────────────────────────────────────────────────────────
    {"id": 1,  "name": "Mancozeb 75% WP",            "category": "Fungicide",     "price": 280,  "unit": "500g",
     "for_disease": ["Late Blight", "Downy Mildew", "Anthracnose"],
     "for_crop": ["Potato", "Tomato", "Grape"],
     "image": "https://placehold.co/200x200?text=Mancozeb",       "buy_url": "https://www.bighaat.com"},
    {"id": 2,  "name": "Copper Hydroxide 77% WP",     "category": "Fungicide",     "price": 420,  "unit": "500g",
     "for_disease": ["Bacterial Spot", "Angular Leaf Spot", "Canker"],
     "for_crop": ["Tomato", "Pepper", "Citrus"],
     "image": "https://placehold.co/200x200?text=Copper",          "buy_url": "https://www.bighaat.com"},
    {"id": 3,  "name": "Carbendazim 50% WP",          "category": "Fungicide",     "price": 240,  "unit": "500g",
     "for_disease": ["Powdery Mildew", "Wilt", "Collar Rot"],
     "for_crop": ["Wheat", "Soybean", "Groundnut"],
     "image": "https://placehold.co/200x200?text=Carbendazim",     "buy_url": "https://www.bighaat.com"},
    {"id": 4,  "name": "Propiconazole 25% EC",        "category": "Fungicide",     "price": 380,  "unit": "250ml",
     "for_disease": ["Rust", "Sheath Blight", "Tikka Leaf Spot"],
     "for_crop": ["Wheat", "Rice", "Groundnut"],
     "image": "https://placehold.co/200x200?text=Propiconazole",   "buy_url": "https://www.bighaat.com"},
    {"id": 5,  "name": "Hexaconazole 5% EC",          "category": "Fungicide",     "price": 320,  "unit": "250ml",
     "for_disease": ["Powdery Mildew", "Rust", "Scab"],
     "for_crop": ["Mango", "Grapes", "Coffee"],
     "image": "https://placehold.co/200x200?text=Hexaconazole",    "buy_url": "https://www.bighaat.com"},
    {"id": 6,  "name": "Tebuconazole 25.9% EC",       "category": "Fungicide",     "price": 460,  "unit": "250ml",
     "for_disease": ["Sheath Blight", "Brown Rust", "Bakanae"],
     "for_crop": ["Rice", "Wheat", "Barley"],
     "image": "https://placehold.co/200x200?text=Tebuconazole",    "buy_url": "https://www.bighaat.com"},
    {"id": 7,  "name": "Metalaxyl 35% WS",            "category": "Fungicide",     "price": 510,  "unit": "100g",
     "for_disease": ["Downy Mildew", "Damping Off", "Late Blight"],
     "for_crop": ["Potato", "Soybean", "Pearl Millet"],
     "image": "https://placehold.co/200x200?text=Metalaxyl",       "buy_url": "https://www.bighaat.com"},
    {"id": 8,  "name": "Azoxystrobin 23% SC",         "category": "Fungicide",     "price": 680,  "unit": "100ml",
     "for_disease": ["Early Blight", "Anthracnose", "Powdery Mildew"],
     "for_crop": ["Tomato", "Mango", "Grapes"],
     "image": "https://placehold.co/200x200?text=Azoxystrobin",    "buy_url": "https://www.bighaat.com"},
    {"id": 9,  "name": "Chlorothalonil 75% WP",       "category": "Fungicide",     "price": 350,  "unit": "500g",
     "for_disease": ["Early Blight", "Late Blight", "Sigatoka"],
     "for_crop": ["Potato", "Banana", "Vegetables"],
     "image": "https://placehold.co/200x200?text=Chlorothalonil",  "buy_url": "https://www.bighaat.com"},
    {"id": 10, "name": "Difenconazole 25% EC",        "category": "Fungicide",     "price": 520,  "unit": "100ml",
     "for_disease": ["Scab", "Brown Rot", "Alternaria Blight"],
     "for_crop": ["Apple", "Potato", "Onion"],
     "image": "https://placehold.co/200x200?text=Difenconazole",   "buy_url": "https://www.bighaat.com"},
    {"id": 11, "name": "Sulphur 80% WDG",             "category": "Fungicide",     "price": 180,  "unit": "1kg",
     "for_disease": ["Powdery Mildew", "Mite", "Rust"],
     "for_crop": ["Grapes", "Vegetables", "Fruit Crops"],
     "image": "https://placehold.co/200x200?text=Sulphur",         "buy_url": "https://www.bighaat.com"},
    {"id": 12, "name": "Kasugamycin 3% SL",           "category": "Fungicide",     "price": 390,  "unit": "250ml",
     "for_disease": ["Blast", "Bacterial Blight", "Damping Off"],
     "for_crop": ["Rice", "Tomato", "Chilli"],
     "image": "https://placehold.co/200x200?text=Kasugamycin",     "buy_url": "https://www.bighaat.com"},

    # ── Insecticides ─────────────────────────────────────────────────────────
    {"id": 13, "name": "Imidacloprid 70 WG",          "category": "Insecticide",   "price": 350,  "unit": "100g",
     "for_disease": ["Aphid", "Whitefly", "Thrips"],
     "for_crop": ["Cotton", "Rice", "Vegetable"],
     "image": "https://placehold.co/200x200?text=Imidacloprid",    "buy_url": "https://www.bighaat.com"},
    {"id": 14, "name": "Chlorpyrifos 20% EC",         "category": "Insecticide",   "price": 260,  "unit": "500ml",
     "for_disease": ["Termite", "Stem Borer", "Pod Borer"],
     "for_crop": ["Maize", "Soybean", "Sugarcane"],
     "image": "https://placehold.co/200x200?text=Chlorpyrifos",    "buy_url": "https://www.bighaat.com"},
    {"id": 15, "name": "Lambda-cyhalothrin 5% EC",    "category": "Insecticide",   "price": 310,  "unit": "250ml",
     "for_disease": ["Bollworm", "Pod Borer", "Leaf Folder"],
     "for_crop": ["Cotton", "Pulses", "Rice"],
     "image": "https://placehold.co/200x200?text=LambdaCyhalothrin","buy_url": "https://www.bighaat.com"},
    {"id": 16, "name": "Thiamethoxam 25% WG",         "category": "Insecticide",   "price": 420,  "unit": "100g",
     "for_disease": ["Whitefly", "Aphid", "Brown Plant Hopper"],
     "for_crop": ["Rice", "Cotton", "Vegetables"],
     "image": "https://placehold.co/200x200?text=Thiamethoxam",    "buy_url": "https://www.bighaat.com"},
    {"id": 17, "name": "Emamectin Benzoate 5% SG",   "category": "Insecticide",   "price": 480,  "unit": "100g",
     "for_disease": ["Diamond Back Moth", "Fruit Borer", "Leaf Miner"],
     "for_crop": ["Cabbage", "Tomato", "Brinjal"],
     "image": "https://placehold.co/200x200?text=EmamectinBenzoate","buy_url": "https://www.bighaat.com"},
    {"id": 18, "name": "Fipronil 5% SC",              "category": "Insecticide",   "price": 390,  "unit": "250ml",
     "for_disease": ["Stem Borer", "Brown Plant Hopper", "Termite"],
     "for_crop": ["Rice", "Sugarcane", "Maize"],
     "image": "https://placehold.co/200x200?text=Fipronil",        "buy_url": "https://www.bighaat.com"},
    {"id": 19, "name": "Cypermethrin 25% EC",         "category": "Insecticide",   "price": 280,  "unit": "250ml",
     "for_disease": ["Bollworm", "Caterpillar", "Aphid"],
     "for_crop": ["Cotton", "Vegetables", "Pulses"],
     "image": "https://placehold.co/200x200?text=Cypermethrin",    "buy_url": "https://www.bighaat.com"},
    {"id": 20, "name": "Acephate 75% SP",             "category": "Insecticide",   "price": 240,  "unit": "500g",
     "for_disease": ["Thrips", "Aphid", "Leaf Miner"],
     "for_crop": ["Chilli", "Groundnut", "Cotton"],
     "image": "https://placehold.co/200x200?text=Acephate",        "buy_url": "https://www.bighaat.com"},
    {"id": 21, "name": "Spinosad 45% SC",             "category": "Insecticide",   "price": 720,  "unit": "100ml",
     "for_disease": ["Fruit Fly", "Leaf Miner", "Thrips"],
     "for_crop": ["Mango", "Tomato", "Capsicum"],
     "image": "https://placehold.co/200x200?text=Spinosad",        "buy_url": "https://www.bighaat.com"},
    {"id": 22, "name": "Indoxacarb 15.8% EC",         "category": "Insecticide",   "price": 560,  "unit": "100ml",
     "for_disease": ["Spodoptera", "Bollworm", "Cutworm"],
     "for_crop": ["Cotton", "Maize", "Vegetables"],
     "image": "https://placehold.co/200x200?text=Indoxacarb",      "buy_url": "https://www.bighaat.com"},
    {"id": 23, "name": "Clothianidin 50% WDG",        "category": "Insecticide",   "price": 650,  "unit": "100g",
     "for_disease": ["Brown Plant Hopper", "Whitefly", "Aphid"],
     "for_crop": ["Rice", "Cotton", "Potato"],
     "image": "https://placehold.co/200x200?text=Clothianidin",    "buy_url": "https://www.bighaat.com"},

    # ── Bio-Fungicides & Bio-Pesticides ──────────────────────────────────────
    {"id": 24, "name": "Trichoderma Viride",          "category": "Bio-fungicide", "price": 150,  "unit": "1kg",
     "for_disease": ["Damping off", "Root Rot", "Wilt"],
     "for_crop": ["Tomato", "Wheat", "Cotton"],
     "image": "https://placehold.co/200x200?text=Trichoderma",     "buy_url": "https://www.bighaat.com"},
    {"id": 25, "name": "Neem Oil 1500 PPM",           "category": "Bio-Pesticide", "price": 120,  "unit": "500ml",
     "for_disease": ["Powdery Mildew", "Aphid", "Mite"],
     "for_crop": ["All crops"],
     "image": "https://placehold.co/200x200?text=NeemOil",         "buy_url": "https://www.bighaat.com"},
    {"id": 26, "name": "Beauveria Bassiana 1.15% WP", "category": "Bio-Pesticide", "price": 200,  "unit": "500g",
     "for_disease": ["Whitefly", "Thrips", "Aphid", "Mite"],
     "for_crop": ["All crops"],
     "image": "https://placehold.co/200x200?text=Beauveria",       "buy_url": "https://www.bighaat.com"},
    {"id": 27, "name": "Metarhizium Anisopliae",      "category": "Bio-Pesticide", "price": 180,  "unit": "500g",
     "for_disease": ["White Grub", "Termite", "Root Weevil"],
     "for_crop": ["Sugarcane", "Maize", "Groundnut"],
     "image": "https://placehold.co/200x200?text=Metarhizium",     "buy_url": "https://www.bighaat.com"},
    {"id": 28, "name": "Pseudomonas Fluorescens",     "category": "Bio-fungicide", "price": 160,  "unit": "500g",
     "for_disease": ["Wilt", "Root Rot", "Damping Off"],
     "for_crop": ["Tomato", "Brinjal", "Pepper"],
     "image": "https://placehold.co/200x200?text=Pseudomonas",     "buy_url": "https://www.bighaat.com"},
    {"id": 29, "name": "Bacillus Thuringiensis (Bt)", "category": "Bio-Pesticide", "price": 240,  "unit": "500g",
     "for_disease": ["Bollworm", "Caterpillar", "Diamond Back Moth"],
     "for_crop": ["Cotton", "Cabbage", "Vegetables"],
     "image": "https://placehold.co/200x200?text=BtInsecticide",   "buy_url": "https://www.bighaat.com"},
    {"id": 30, "name": "NPV (Nuclear Polyhedrosis Virus)", "category": "Bio-Pesticide", "price": 280, "unit": "250ml",
     "for_disease": ["Spodoptera", "Helicoverpa", "Leaf Folder"],
     "for_crop": ["Cotton", "Tomato", "Chickpea"],
     "image": "https://placehold.co/200x200?text=NPV",             "buy_url": "https://www.bighaat.com"},

    # ── Herbicides ───────────────────────────────────────────────────────────
    {"id": 31, "name": "Glyphosate 41% SL",           "category": "Herbicide",     "price": 220,  "unit": "500ml",
     "for_disease": [],
     "for_crop": ["Plantation crops", "Orchards", "Non-crop areas"],
     "image": "https://placehold.co/200x200?text=Glyphosate",      "buy_url": "https://www.bighaat.com"},
    {"id": 32, "name": "2,4-D Amine Salt 58% SL",    "category": "Herbicide",     "price": 160,  "unit": "500ml",
     "for_disease": [],
     "for_crop": ["Wheat", "Rice", "Maize"],
     "image": "https://placehold.co/200x200?text=2-4D",            "buy_url": "https://www.bighaat.com"},
    {"id": 33, "name": "Pendimethalin 30% EC",        "category": "Herbicide",     "price": 280,  "unit": "500ml",
     "for_disease": [],
     "for_crop": ["Wheat", "Cotton", "Soybean", "Onion"],
     "image": "https://placehold.co/200x200?text=Pendimethalin",   "buy_url": "https://www.bighaat.com"},
    {"id": 34, "name": "Atrazine 50% WP",             "category": "Herbicide",     "price": 200,  "unit": "500g",
     "for_disease": [],
     "for_crop": ["Maize", "Sugarcane", "Sorghum"],
     "image": "https://placehold.co/200x200?text=Atrazine",        "buy_url": "https://www.bighaat.com"},
    {"id": 35, "name": "Clodinafop Propargyl 15% WP","category": "Herbicide",     "price": 340,  "unit": "160g",
     "for_disease": [],
     "for_crop": ["Wheat"],
     "image": "https://placehold.co/200x200?text=Clodinafop",      "buy_url": "https://www.bighaat.com"},
    {"id": 36, "name": "Bispyribac Sodium 10% SC",   "category": "Herbicide",     "price": 380,  "unit": "100ml",
     "for_disease": [],
     "for_crop": ["Rice"],
     "image": "https://placehold.co/200x200?text=Bispyribac",      "buy_url": "https://www.bighaat.com"},

    # ── Fertilizers ──────────────────────────────────────────────────────────
    {"id": 37, "name": "DAP Fertilizer",              "category": "Fertilizer",    "price": 1350, "unit": "50kg",
     "for_disease": [],
     "for_crop": ["Wheat", "Rice", "Maize", "Soybean"],
     "image": "https://placehold.co/200x200?text=DAP",             "buy_url": "https://www.bighaat.com"},
    {"id": 38, "name": "Urea (Neem Coated)",          "category": "Fertilizer",    "price": 280,  "unit": "45kg",
     "for_disease": [],
     "for_crop": ["Rice", "Wheat", "Sugarcane"],
     "image": "https://placehold.co/200x200?text=Urea",            "buy_url": "https://www.bighaat.com"},
    {"id": 39, "name": "NPK 19:19:19 Water Soluble",  "category": "Fertilizer",    "price": 520,  "unit": "1kg",
     "for_disease": [],
     "for_crop": ["Vegetable", "Fruit", "Flower"],
     "image": "https://placehold.co/200x200?text=NPK+19-19-19",    "buy_url": "https://www.bighaat.com"},
    {"id": 40, "name": "Potassium Nitrate (13:0:45)", "category": "Fertilizer",    "price": 480,  "unit": "1kg",
     "for_disease": [],
     "for_crop": ["Grapes", "Tomato", "Potato"],
     "image": "https://placehold.co/200x200?text=KNO3",            "buy_url": "https://www.bighaat.com"},
    {"id": 41, "name": "Calcium Nitrate",             "category": "Fertilizer",    "price": 360,  "unit": "1kg",
     "for_disease": ["Blossom End Rot", "Tip Burn"],
     "for_crop": ["Tomato", "Capsicum", "Lettuce"],
     "image": "https://placehold.co/200x200?text=CaNO3",           "buy_url": "https://www.bighaat.com"},
    {"id": 42, "name": "Sulphate of Potash (SOP)",   "category": "Fertilizer",    "price": 620,  "unit": "1kg",
     "for_disease": [],
     "for_crop": ["Potato", "Onion", "Tobacco"],
     "image": "https://placehold.co/200x200?text=SOP",             "buy_url": "https://www.bighaat.com"},
    {"id": 43, "name": "Magnesium Sulphate",          "category": "Fertilizer",    "price": 160,  "unit": "1kg",
     "for_disease": ["Magnesium Deficiency", "Yellowing"],
     "for_crop": ["Tomato", "Citrus", "Banana"],
     "image": "https://placehold.co/200x200?text=MgSO4",           "buy_url": "https://www.bighaat.com"},
    {"id": 44, "name": "Zinc Sulphate 21%",           "category": "Fertilizer",    "price": 180,  "unit": "1kg",
     "for_disease": ["Zinc Deficiency", "Khaira Disease"],
     "for_crop": ["Rice", "Wheat", "Maize"],
     "image": "https://placehold.co/200x200?text=ZnSO4",           "buy_url": "https://www.bighaat.com"},
    {"id": 45, "name": "Ferrous Sulphate",            "category": "Fertilizer",    "price": 140,  "unit": "1kg",
     "for_disease": ["Iron Chlorosis", "Yellowing"],
     "for_crop": ["Vegetable", "Citrus", "All crops"],
     "image": "https://placehold.co/200x200?text=FeSO4",           "buy_url": "https://www.bighaat.com"},
    {"id": 46, "name": "Boron 20% (Borax)",          "category": "Fertilizer",    "price": 220,  "unit": "500g",
     "for_disease": ["Boron Deficiency", "Hollow Heart"],
     "for_crop": ["Sunflower", "Groundnut", "Cauliflower"],
     "image": "https://placehold.co/200x200?text=Boron",           "buy_url": "https://www.bighaat.com"},
    {"id": 47, "name": "MOP (Muriate of Potash)",    "category": "Fertilizer",    "price": 780,  "unit": "50kg",
     "for_disease": [],
     "for_crop": ["Sugarcane", "Banana", "Cotton"],
     "image": "https://placehold.co/200x200?text=MOP",             "buy_url": "https://www.bighaat.com"},
    {"id": 48, "name": "SSP (Single Super Phosphate)","category": "Fertilizer",    "price": 420,  "unit": "50kg",
     "for_disease": [],
     "for_crop": ["Groundnut", "Oilseed", "Pulses"],
     "image": "https://placehold.co/200x200?text=SSP",             "buy_url": "https://www.bighaat.com"},

    # ── Organic / Soil Amendment ──────────────────────────────────────────────
    {"id": 49, "name": "Vermicompost",                "category": "Organic",       "price": 200,  "unit": "5kg",
     "for_disease": [],
     "for_crop": ["Vegetable", "Fruit", "Flower"],
     "image": "https://placehold.co/200x200?text=Vermicompost",    "buy_url": "https://www.bighaat.com"},
    {"id": 50, "name": "Organic Humic Acid 98%",      "category": "Organic",       "price": 280,  "unit": "500g",
     "for_disease": [],
     "for_crop": ["All crops"],
     "image": "https://placehold.co/200x200?text=HumicAcid",       "buy_url": "https://www.bighaat.com"},
    {"id": 51, "name": "Seaweed Extract Liquid",      "category": "Organic",       "price": 350,  "unit": "500ml",
     "for_disease": [],
     "for_crop": ["Vegetable", "Fruit", "Flower"],
     "image": "https://placehold.co/200x200?text=Seaweed",         "buy_url": "https://www.bighaat.com"},
    {"id": 52, "name": "Neem Cake",                   "category": "Organic",       "price": 120,  "unit": "5kg",
     "for_disease": ["Nematode", "Soil Insects"],
     "for_crop": ["Vegetable", "Fruit", "All crops"],
     "image": "https://placehold.co/200x200?text=NeemCake",        "buy_url": "https://www.bighaat.com"},
    {"id": 53, "name": "Bone Meal (Steamed)",         "category": "Organic",       "price": 240,  "unit": "5kg",
     "for_disease": [],
     "for_crop": ["Vegetable", "Flower", "Fruit"],
     "image": "https://placehold.co/200x200?text=BoneMeal",        "buy_url": "https://www.bighaat.com"},
    {"id": 54, "name": "Panchagavya (Organic Growth Promoter)", "category": "Organic", "price": 190, "unit": "1L",
     "for_disease": [],
     "for_crop": ["All crops"],
     "image": "https://placehold.co/200x200?text=Panchagavya",     "buy_url": "https://www.bighaat.com"},
    {"id": 55, "name": "Bio NPK Consortium",          "category": "Organic",       "price": 160,  "unit": "500g",
     "for_disease": [],
     "for_crop": ["All crops"],
     "image": "https://placehold.co/200x200?text=BioNPK",          "buy_url": "https://www.bighaat.com"},
    {"id": 56, "name": "Castor Cake",                 "category": "Organic",       "price": 90,   "unit": "5kg",
     "for_disease": ["Nematode"],
     "for_crop": ["Vegetable", "Sugarcane", "All crops"],
     "image": "https://placehold.co/200x200?text=CastorCake",      "buy_url": "https://www.bighaat.com"},

    # ── Growth Regulators / PGR ───────────────────────────────────────────────
    {"id": 57, "name": "Gibberellic Acid 0.001% L",  "category": "PGR",           "price": 290,  "unit": "250ml",
     "for_disease": [],
     "for_crop": ["Grapes", "Mango", "Tomato"],
     "image": "https://placehold.co/200x200?text=GA3",             "buy_url": "https://www.bighaat.com"},
    {"id": 58, "name": "Ethephon 39% SL",             "category": "PGR",           "price": 260,  "unit": "250ml",
     "for_disease": [],
     "for_crop": ["Banana", "Pineapple", "Rubber"],
     "image": "https://placehold.co/200x200?text=Ethephon",        "buy_url": "https://www.bighaat.com"},
    {"id": 59, "name": "Triacontanol 0.05% EC",       "category": "PGR",           "price": 180,  "unit": "250ml",
     "for_disease": [],
     "for_crop": ["Rice", "Wheat", "Vegetable"],
     "image": "https://placehold.co/200x200?text=Triacontanol",    "buy_url": "https://www.bighaat.com"},
    {"id": 60, "name": "Paclobutrazol 23% SC",        "category": "PGR",           "price": 420,  "unit": "250ml",
     "for_disease": [],
     "for_crop": ["Mango", "Sugarcane"],
     "image": "https://placehold.co/200x200?text=Paclobutrazol",   "buy_url": "https://www.bighaat.com"},

    # ── Miticides / Acaricides ────────────────────────────────────────────────
    {"id": 61, "name": "Abamectin 1.8% EC",           "category": "Miticide",      "price": 560,  "unit": "250ml",
     "for_disease": ["Red Spider Mite", "Two Spotted Mite", "Mite"],
     "for_crop": ["Vegetable", "Fruit", "Ornamentals"],
     "image": "https://placehold.co/200x200?text=Abamectin",       "buy_url": "https://www.bighaat.com"},
    {"id": 62, "name": "Dicofol 18.5% EC",            "category": "Miticide",      "price": 310,  "unit": "250ml",
     "for_disease": ["Red Spider Mite", "Mite"],
     "for_crop": ["Cotton", "Apple", "Citrus"],
     "image": "https://placehold.co/200x200?text=Dicofol",         "buy_url": "https://www.bighaat.com"},
    {"id": 63, "name": "Spiromesifen 22.9% SC",       "category": "Miticide",      "price": 680,  "unit": "100ml",
     "for_disease": ["Mite", "Whitefly"],
     "for_crop": ["Tomato", "Chilli", "Cucumber"],
     "image": "https://placehold.co/200x200?text=Spiromesifen",    "buy_url": "https://www.bighaat.com"},

    # ── Nematicides ───────────────────────────────────────────────────────────
    {"id": 64, "name": "Carbofuran 3% CG",            "category": "Nematicide",    "price": 240,  "unit": "3kg",
     "for_disease": ["Root Knot Nematode", "Stem Nematode"],
     "for_crop": ["Banana", "Tomato", "Groundnut"],
     "image": "https://placehold.co/200x200?text=Carbofuran",      "buy_url": "https://www.bighaat.com"},
    {"id": 65, "name": "Fluopyram 34.48% SC",         "category": "Nematicide",    "price": 890,  "unit": "100ml",
     "for_disease": ["Root Knot Nematode", "Cyst Nematode"],
     "for_crop": ["Tomato", "Potato", "Banana"],
     "image": "https://placehold.co/200x200?text=Fluopyram",       "buy_url": "https://www.bighaat.com"},

    # ── Irrigation & Soil Tools ───────────────────────────────────────────────
    {"id": 66, "name": "Drip Irrigation Starter Kit","category": "Equipment",     "price": 2800, "unit": "Set",
     "for_disease": [],
     "for_crop": ["Vegetable", "Fruit", "Sugarcane"],
     "image": "https://placehold.co/200x200?text=DripKit",         "buy_url": "https://www.bighaat.com"},
    {"id": 67, "name": "Soil pH Meter (Digital)",     "category": "Equipment",     "price": 950,  "unit": "Piece",
     "for_disease": [],
     "for_crop": ["All crops"],
     "image": "https://placehold.co/200x200?text=pHMeter",         "buy_url": "https://www.bighaat.com"},
    {"id": 68, "name": "Hand Sprayer (16L Knapsack)", "category": "Equipment",     "price": 1100, "unit": "Piece",
     "for_disease": [],
     "for_crop": ["All crops"],
     "image": "https://placehold.co/200x200?text=Sprayer",         "buy_url": "https://www.bighaat.com"},

    # ── Seeds ─────────────────────────────────────────────────────────────────
    {"id": 69, "name": "Hybrid Tomato Seeds (Arka Rakshak)", "category": "Seeds", "price": 220, "unit": "10g",
     "for_disease": ["Resistant to Tomato Leaf Curl Virus"],
     "for_crop": ["Tomato"],
     "image": "https://placehold.co/200x200?text=TomatoSeed",      "buy_url": "https://www.bighaat.com"},
    {"id": 70, "name": "Hybrid Maize Seeds (DKC 9081)","category": "Seeds",       "price": 480,  "unit": "1kg",
     "for_disease": [],
     "for_crop": ["Maize"],
     "image": "https://placehold.co/200x200?text=MaizeSeed",       "buy_url": "https://www.bighaat.com"},
    {"id": 71, "name": "Soybean Seed (JS 9305)",      "category": "Seeds",         "price": 160,  "unit": "1kg",
     "for_disease": [],
     "for_crop": ["Soybean"],
     "image": "https://placehold.co/200x200?text=SoybeanSeed",     "buy_url": "https://www.bighaat.com"},
    {"id": 72, "name": "Paddy Seed (Pusa Basmati 1509)", "category": "Seeds",     "price": 120,  "unit": "1kg",
     "for_disease": [],
     "for_crop": ["Rice"],
     "image": "https://placehold.co/200x200?text=PaddySeed",       "buy_url": "https://www.bighaat.com"},

    # ── Specialty / Foliar ────────────────────────────────────────────────────
    {"id": 73, "name": "Chelated Micronutrient Mix",  "category": "Micronutrient", "price": 340,  "unit": "500g",
     "for_disease": ["Micronutrient Deficiency", "Chlorosis"],
     "for_crop": ["All crops"],
     "image": "https://placehold.co/200x200?text=MicroMix",        "buy_url": "https://www.bighaat.com"},
    {"id": 74, "name": "Amino Acid Liquid (Foliar)",  "category": "Micronutrient", "price": 310,  "unit": "500ml",
     "for_disease": [],
     "for_crop": ["All crops"],
     "image": "https://placehold.co/200x200?text=AminoAcid",       "buy_url": "https://www.bighaat.com"},
    {"id": 75, "name": "Silicon Solubilizer (Liquid)","category": "Micronutrient", "price": 280,  "unit": "500ml",
     "for_disease": ["Blast", "Powdery Mildew"],
     "for_crop": ["Rice", "Wheat", "Sugarcane"],
     "image": "https://placehold.co/200x200?text=Silicon",         "buy_url": "https://www.bighaat.com"},
]


@market_bp.get("/products")
def products():
    disease = request.args.get("disease", "").lower()
    crop    = request.args.get("crop", "").lower()
    cat     = request.args.get("category", "").lower()

    result = PRODUCTS
    if disease:
        result = [p for p in result
                  if any(disease in d.lower() for d in p["for_disease"])]
    if crop:
        result = [p for p in result
                  if any(crop in c.lower() for c in p["for_crop"])]
    if cat:
        result = [p for p in result if p["category"].lower() == cat]

    return jsonify({"products": result, "count": len(result)})


@market_bp.get("/categories")
def categories():
    cats = list({p["category"] for p in PRODUCTS})
    return jsonify(cats)
